name: Run Manual Test
on: 
  workflow_dispatch:
  inputs:
    specs: 
      description: Comma-separates spec filenames without spaces
      required: true
    brow:
      description: Browser name
      required: true
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Orange Cypress Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser ${{ github.event.inputs.brow }} --spec '${{ github.event.inputs.specs }}'
      